basePath: /api/v1
definitions:
  handler.CreateOpeningRequest:
    properties:
      company:
        type: string
      link:
        type: string
      location:
        type: string
      remote:
        type: boolean
      role:
        type: string
      salary:
        type: integer
    type: object
  handler.CreateOpeningResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.OpeningResponse'
      message:
        type: string
    type: object
  handler.ErrorResponse:
    properties:
      errorCode:
        type: string
      message:
        type: string
    type: object
  schemas.OpeningResponse:
    properties:
      company:
        example: Tech Corp
        type: string
      created_at:
        example: "2025-11-09T21:02:00Z"
        type: string
      deleted_at:
        example: "null"
        type: string
      id:
        example: 1
        type: integer
      link:
        example: https://example.com/job
        type: string
      location:
        example: New York
        type: string
      remote:
        example: true
        type: boolean
      role:
        example: Software Engineer
        type: string
      salary:
        example: 100000
        type: integer
      updated_at:
        example: "2025-11-09T21:02:00Z"
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample API server using Gin, sqlite and documented with Swagger
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Go + Gin + Swagger API Demo
  version: "1.0"
paths:
  /opening:
    post:
      consumes:
      - application/json
      description: Create a new job opening with role, company, and remote status
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.CreateOpeningRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.CreateOpeningResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Create an opening job
      tags:
      - openings
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
